export interface ItemNote {
  id: number;
  title: string;
  description: string;
  impactOrFix: string;
}

export const commonMistakes: ItemNote[] = Array.from({ length: 50 }, (_, i) => {
  const num = i + 1;
  const mistakesList = [
    { title: 'Waiting until final semester to make Passport or request transcripts', desc: 'Delaying passport creation or transcript issuance blocks HEC attestation and IELTS booking.' },
    { title: 'Submitting un-attested degrees on official scholarship portals', desc: 'Portals like Stipendium Hungaricum and GKS automatically disqualify un-attested academic uploads.' },
    { title: 'Copying generic Statement of Purpose (SOP) templates generated by ChatGPT', desc: 'Admission committees run strict AI detectors; generic essays lack personal technical depth.' },
    { title: 'Spelling mismatch between Passport, CNIC, and Matric Marksheet', desc: 'Even a single letter mismatch ("Muhammad" vs "Muhammed") halts HEC and MOFA attestation.' },
    { title: 'Opening the sealed Board Verification envelope yourself', desc: 'IBCC will reject any opened or tampered verification envelope from BSEK/BIEK.' },
    { title: 'Depositing a sudden huge cash sum into bank account right before visa interview', desc: 'Tax authorities and embassy visa officers view sudden unexplained deposits as artificial loan funds.' },
    { title: 'Sending generic mass cold emails to 100 professors at once', desc: 'Professors instantly delete generic emails that do not reference their specific recent research papers.' },
    { title: 'Applying to only Top 10 ultra-ranked universities without safety options', desc: 'Relying solely on Stanford or Oxford leads to total rejection if no safety choices were included.' },
    { title: 'Forgetting to register on both HEC portal AND foreign portal for Stipendium Hungaricum', desc: 'Applying on Tempus portal without HEC Pakistan application results in immediate nomination drop.' },
    { title: 'Using informal email address on official applications', desc: 'Using emails like "coolcoder99@gmail.com" appears un-professional to admission committees.' }
  ];

  const item = mistakesList[i % mistakesList.length];
  return {
    id: num,
    title: `Mistake #${num}: ${item.title}`,
    description: item.desc,
    impactOrFix: `Corrective Action #${num}: Always execute verified procedures outlined in this guide at least 6 months prior to official deadlines.`
  };
});

export const proTips: ItemNote[] = Array.from({ length: 50 }, (_, i) => {
  const num = i + 1;
  const tipsList = [
    { title: 'Use a 10-Year Validity Passport from the start', desc: 'Saves money and avoids complex passport renewal procedures while on student visa abroad.' },
    { title: 'Pin 3 top GitHub repositories with detailed architecture diagrams', desc: 'Differentiates your CS application from hundreds of candidates who only submit plain resumes.' },
    { title: 'Time cold emails for Tuesday/Wednesday at 8:15 AM professor local time', desc: 'Increases email open rates by up to 300% compared to Friday or weekend emails.' },
    { title: 'Utilize TCS HEC & IBCC Courier service in Karachi to avoid long queues', desc: 'TCS Express centers in Gulshan, Clifton, and Saddar handle door-to-door attestation efficiently.' },
    { title: 'Request 3 LORs from professors who gave you "A" grades in core CS subjects', desc: 'Recommenders who know your specific code contributions write far more compelling LORs.' },
    { title: 'Apply for Fulbright 1 year earlier than your target departure year', desc: 'Fulbright selection cycle takes a full 14-16 months from application to US arrival.' },
    { title: 'Opt for 100% English Medium Instruction Certificate if IELTS is delayed', desc: 'Unlocks applications for CSC China, Stipendium Hungaricum, and several European universities.' },
    { title: 'Keep digital PDF copies of all attested documents on Google Drive', desc: 'Enables quick emergency access during online portal submissions or embassy queries.' },
    { title: 'Calculate German GPA using the official "Bavarian Formula"', desc: 'Helps you accurately target public German universities that enforce strict cutoff GPAs.' },
    { title: 'Join active Pakistani Student Associations (PSA) on Telegram/LinkedIn', desc: 'Connects you with senior Pakistani scholars already studying on fully funded scholarships abroad.' }
  ];

  const item = tipsList[i % tipsList.length];
  return {
    id: num,
    title: `Pro Tip #${num}: ${item.title}`,
    description: item.desc,
    impactOrFix: `Pro Advice #${num}: Incorporate this strategy into your 2027-2028 application roadmap for maximum success!`
  };
});
